import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by Hao Ico",
  icons: [
    {
      url: "/ico.jpg",
      rel: "page-icon",
      type: "image/jpg"
    }
  ]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <script src="/SetIcon.js" defer></script>
      </body>
    </html>
  );
}
